name: First Workflow
# manually trigger workflow
on: workflow_dispatch  
jobs:
  first-job:
    runs-on: macos-26
    steps:
      - name: Print greetings
        run: echo "Hello World!"
      - name: Print greetings
        run: echo "Done Bye!"
       
